---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data01
  labels:
    app: redis
    role: master
    tier: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data02
  labels:
    app: redis
    role: slave
    tier: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
