apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../stateless

patches:
  - patch: |-
      - op: replace
        path: "/apiVersion"
        value: "apps/v1beta2"
    target:
      kind: Deployment
      version: v1
